services:
  reporting_proposal:
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.29
    entrypoint: ""
    volumes:
      - .:/home/decidim/module
      - bundle:/home/decidim/app/vendor
      - node_modules:/home/decidim/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://decidim:pleaseChangeMe@reporting-proposal-pg:5432/decidim
      - DATABASE_HOST=reporting-proposal-pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DEV_MODULE=decidim-reporting_proposals
      - RAILS_ENV=development
      - MAPS_PROVIDER=osm
      - MAPS_DYNAMIC_URL=https://tile.openstreetmap.org/{z}/{x}/{y}.png
      - MAPS_STATIC_URL=https://tile.openstreetmap.org/{z}/{x}/{y}.png
      - MAPS_ATTRIBUTION=<a href="https://www.openstreetmap.org/copyright" target="_blank">© OpenStreetMap</a> contributors
      - MAPS_GEOCODING_HOST=https://nominatim.openstreetmap.org
    depends_on:
      - reporting-proposal-pg
    ports:
      - 3000:3000
    links:
      - reporting-proposal-pg

  reporting-proposal-pg:
    image: postgres:15
    volumes:
      - reporting-proposal-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=decidim
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pleaseChangeMe

volumes:
  node_modules: {}
  bundle: {}
  reporting-proposal-pg-data: {}
